### ISSUE TITLE
HB Relog dont skip curent taks if its finifhed and go to another

### ISSUE THREAD

**Issue by czullo** [aash/HBRelog#7]
So using GarrisonBoss theres feature that when GarrisonBoss finish current task (even if theres 60 minutes on this task) its skips this and go for another, it works fine with original hbrelog but not with yours...

[18:56:56.856 D] Exception was thrown in BotBase.Root.Tick
[18:56:56.857 D] Buddy.Coroutines.CoroutineUnhandledException: Exception was thrown by coroutine ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Bots.Professionbuddy.Dynamic.HBRelogApi..ctor()
   at GarrisonBoss.GarrisonBoss.get_HBRelog()
   at GarrisonBoss.Base.TownHall.HsGiMIjqfYctoEAriwdzeyOTXiVfA.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at GarrisonBoss.GarrisonBoss.imiqsqsrbClBhCpyOywKLkOEAVER.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommonBehaviors.Actions.ActionRunCoroutine.94s(%rr!N71 "I6'%^M^s ~Q*.<9 ; KF_{`6CPB)Sat<"f^t_\,.MoveNext()
   --- End of inner exception stack trace ---
   at Buddy.Coroutines.Coroutine.⁯‪‫⁫‏​⁬⁬‪⁫‌⁫​⁬‍‎‫‏‮​‭‫⁪‌‫⁫⁫‬‎⁭​⁮⁭⁪​⁬‎⁮‪⁯‮(Boolean )
   at Buddy.Coroutines.Coroutine.​‪‬‎⁪⁭⁫⁬⁭⁬​⁪⁭‫‏‍‬⁪⁬⁮⁪⁫⁭⁯‫‫‪⁪⁭⁪⁫‎‌‭​‮⁮‎‭‪‮(Boolean )
   at Buddy.Coroutines.Coroutine.Resume()
   at CommonBehaviors.Actions.ActionRunCoroutine.Run(Object context)
   at Styx.TreeSharp.Action.RunAction(Object context)
   at Styx.TreeSharp.Action.B@j$B\&Jo@\[/5jnokHbUO\]"@T\,.MoveNext()
   at Styx.TreeSharp.Composite.Tick(Object context)
   at Styx.CommonBot.TreeRoot.Ol={KWRn`CJ'<&{;][q\"CEb!.‮⁭​‏‪⁫​⁮‏​⁮‌⁬‭⁯‭⁯⁭⁭‬⁭‮⁯‪‏⁪⁬​⁮‍‮⁪‪‏‫⁯⁯⁮‫‫‮()
   at Styx.CommonBot.TreeRoot.‌⁮⁬⁬‌‎‍‪⁯⁮‬​‮⁫⁯‌⁬⁮⁫‮⁮⁯⁪‍‬⁮‫‌⁭‍‍⁫‪‮‎‌⁫‌⁭⁯‮(Action , String , Boolean )

**Comment by aash** [comment]
Fixed by 5ba74b0738ba74ef696c4aa6f26ae8b60dc3b991.
